### ISSUE TITLE
预训练模型文件损坏

### ISSUE THREAD

**Issue by Tongbook** [LUMIA-Group/Leveraging-Self-Supervised-Learning-for-AVSR#1]
您好，您发布的预训练模型100MB的压缩包是损坏的，我这尝试多次都没有成功

**Comment by PeiyuChen1005** [comment]
Tongbook你好，可以麻烦你提供一下你下载的预训练模型的名字和下载链接吗？或许你说的是MoCo或者wav2vec2的预训练模型？

**Comment by ouwen18** [comment]
我下载的mocov2预训练模型也是损坏的，请问哪里可以下载到正常的
