### ISSUE TITLE
关于seed的设置

### ISSUE THREAD

**Issue by MIss-luoyu** [LUMIA-Group/Leveraging-Self-Supervised-Learning-for-AVSR#2]
感谢您的开源工作！
请问，在您的工作中是否对seed这个参数进行了多次调试？据我所知，seed似乎对实验能产生相对重要的影响。如果您有调试您都是怎么调试的呢？

**Comment by hantek** [comment]
您好，我们没有对seed进行调试。

对于LRS2这样的大规模数据集，seed对模型的影响很有限，并且seed引起的只是模型结果的随机噪声，实际上不应该去调seed。
